In [1]:
%matplotlib inline

In [2]:
%%bash
conda install pytorch torchvision -c soumith

Process is terminated.



Tensors
=======

Tensors behave almost exactly the same way in PyTorch as they do in
Torch.

Create a tensor of size (5 x 7) with uninitialized memory:




In [2]:
import torch
a = torch.FloatTensor(5, 7)

Initialize a tensor randomized with a normal distribution with mean=0, var=1:



In [3]:
a = torch.randn(5, 7)
print(a)
print(a.size())

tensor([[ 0.7292, -0.6780, -0.8854, -0.6688, -0.2979, -0.2549, -0.4290],
        [-0.2959, -2.1381,  0.3735, -1.6117, -0.5397, -0.8251, -0.0944],
        [-0.3142, -1.3450, -0.9411,  0.2496,  0.2823, -0.2959, -0.0048],
        [-0.1951, -0.8663, -0.2173,  2.1329, -0.6608,  0.5312, -0.9109],
        [ 0.2669,  0.5877,  0.9939,  0.0922, -1.3421,  0.8412, -0.9142]])
torch.Size([5, 7])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Inplace / Out-of-place
----------------------

The first difference is that ALL operations on the tensor that operate
in-place on it will have an ``_`` postfix. For example, ``add`` is the
out-of-place version, and ``add_`` is the in-place version.



In [4]:
a.fill_(3.5)
# a has now been filled with the value 3.5

b = a.add(4.0)
# a is still filled with 3.5
# new tensor b is returned with values 3.5 + 4.0 = 7.5

print(a, b)

tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000, 3.5000]]) tensor([[7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000, 7.5000]])


Some operations like ``narrow`` do not have in-place versions, and
hence, ``.narrow_`` does not exist. Similarly, some operations like
``fill_`` do not have an out-of-place version, so ``.fill`` does not
exist.

Zero Indexing
-------------

Another difference is that Tensors are zero-indexed. (In lua, tensors are
one-indexed)



In [5]:
b = a[0, 3]  # select 1st row, 4th column from a

Tensors can be also indexed with Python's slicing



In [6]:
b = a[:, 3:5]  # selects all rows, 4th column and  5th column from a

No camel casing
---------------

The next small difference is that all functions are now NOT camelCase
anymore. For example ``indexAdd`` is now called ``index_add_``



In [7]:
x = torch.ones(5, 5)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [8]:
z = torch.Tensor(5, 2)
z[:, 0] = 10
z[:, 1] = 100
print(z)

tensor([[ 10., 100.],
        [ 10., 100.],
        [ 10., 100.],
        [ 10., 100.],
        [ 10., 100.]])


In [9]:
x.index_add_(1, torch.LongTensor([4, 0]), z)
print(x)

tensor([[101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.],
        [101.,   1.,   1.,   1.,  11.]])


Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.
The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [10]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [11]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [12]:
a.add_(1)
print(a)
print(b) 	# see how the numpy array changed in value

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

CUDA Tensors are nice and easy in pytorch, and transfering a CUDA tensor
from the CPU to GPU will retain its underlying type.



In [14]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    # creates a LongTensor and transfers it
    # to GPU as torch.cuda.LongTensor
    a = torch.LongTensor(10).fill_(3).cuda()
    print(type(a))
    b = a.cpu()
    # transfers it to CPU, back to
    # being a torch.LongTensor

In [27]:
import torch.nn.functional as F
t4d = torch.rand(3, 3)
t4d2 = torch.rand(3, 3)
print(t4d)
p1d = (0, 1, 2,2 ) # pad last dim by 1 on each side
out = F.pad(t4d, p1d, "constant", 0)  # effectively zero padding
print(out)
print(t4d+t4d2)

tensor([[0.6321, 0.7192, 0.2566],
        [0.5308, 0.1696, 0.3069],
        [0.8424, 0.9149, 0.4901]])
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.6321, 0.7192, 0.2566, 0.0000],
        [0.5308, 0.1696, 0.3069, 0.0000],
        [0.8424, 0.9149, 0.4901, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])
tensor([[1.5283, 0.8030, 0.8572],
        [0.9450, 0.7898, 1.3008],
        [1.4434, 1.3736, 0.5900]])
